### ISSUE TITLE
dnf module install 389-ds fails

### ISSUE THREAD

**Issue by alexxa** [modularity-modules/389-ds#1]
Error: 
Problem 1: conflicting requests
  - nothing provides libtcmalloc.so.4()(64bit) needed by 389-ds-base-libs-1.3.7.4-1.module_506864e9.x86_64
Problem 2: conflicting requests
  - nothing provides libtcmalloc.so.4()(64bit) needed by 389-ds-base-1.3.7.4-1.module_506864e9.x86_64"

See console_output: https://ci.centos.org/job/fedora-qa-compose_tester/

**Comment by alexxa** [comment]
@KarstenHopp

**Comment by KarstenHopp** [comment]
The latest 389-ds module in the '1.2' branch includes gperftools-libs which provides the missing library.
Composes are currently done with the master branch afaik, so this will take a while to show up in our composes.
