### ISSUE TITLE
fails to install (missing deps)

### ISSUE THREAD

**Issue by whitel** [modularity-modules/389-ds#2]
-------------------------------` DNF ----------------------------------
    Installed Packages
    dnf.noarch                             2.7.3-1.module_e1d44a88.modularity.1.3fb9e5c                          @anaconda
    libdnf.x86_64                          0.10.1-2.module_e1d44a88.modularity.1                                 @anaconda
    ----------------------------------------------------------------------
    Image built with (KOJI composes):
                    GIT:            https://github.com/container-images/boltron-27
                    Base:           Fedora-Modular-Bikeshed-20171011.n.0
    Image running aginst (KOJI Composes):
                    Bike:   Fedora-Modular-Bikeshed-20171012.n.0

    $ dnf module install 389-ds
    Fedora - Bikeshed - Developmental packages for the next Fedora release                8.5 MB/s | 3.5 MB     00:00    
    Last metadata expiration check: 0:00:00 ago on Fri 13 Oct 2017 02:44:48 PM UTC.
    Error: 
     Problem 1: conflicting requests
      - nothing provides libtcmalloc.so.4()(64bit) needed by 389-ds-base-libs-1.3.7.4-1.module_506864e9.x86_64
     Problem 2: conflicting requests
      - nothing provides libtcmalloc.so.4()(64bit) needed by 389-ds-base-1.3.7.4-1.module_506864e9.x86_64

**Comment by KarstenHopp** [comment]
This is fixed in 389-ds-1.2, boltron-f27 is still using the master stream
